name: CI

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    
    - name: Setup Rust components
      run: rustup component add rustfmt clippy

    - name: Show Rust version
      run: rustc --version && cargo --version && rustup show

    - name: Format check
      run: cargo fmt -- --check
      working-directory: code-stats-rs
    
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: code-stats-rs
    
    - name: Test
      run: cargo test
      working-directory: code-stats-rs
    
    - name: Build
      run: cargo build --release
      working-directory: code-stats-rs